### PR TITLE
Fix Attributes/ignore case on SubItems for StringLiterals.

### PR DESCRIPTION
**Pull request by jsm174**
This fixes the last PR, by correctly passing in `parentAttributes` into `createRule` for SubItems.

### CODE REVIEW

**Comment by menduz** [comment]
Please add some tests to validate we wont break this behavior in the future

**Comment by jsm174** [comment]
Okay. Should I create a new test file, or add to `NewLang.spec.ts`?

**Comment by menduz** [comment]
I'd create a new one, NewLang is a huge test and after a year of writing it it scares every time I see t.

**Comment by jsm174** [comment]
> I'd create a new one, NewLang is a huge test and after a year of writing it it scares every time I see t.

😃 Test cases written. Thanks!

**Comment by menduz** [comment]
`+ ebnf@1.7.4`

**Pull request merged**
